### ISSUE TITLE
Feature Request: URL Screencaps

### ISSUE THREAD

**Issue by AJB99** [6px-io/6px-api-docs#6]
Hi folks,

If you offered an API where I could send through a URL and get a resulting screen cap according to the params that I sent through (resolution, window size, etc.) then 6px would be perfect for the app that I'm building. Any idea if/when you'll offer this?

6px looks like an excellent service. It's amazing how difficult it is to find a service that offers image processing with the ability to save the resulting files to my *own* S3 bucket. Cloudinary would have my business except for the fact that they want to force me to store my files with them. Blitline is just a crappy API.

**Comment by nparsons08** [comment]
Our team is currently discussing the possibility of integrating screen captures into our API. As of now, we agree that it would be a great addition.

We set out to make 6px a powerful API for developers, ensuring that YOUR images can be stored where YOU choose.

We'll keep this open until we have a solid date on the roadmap. Stay tuned!
