### ISSUE TITLE
Max image filesize

### ISSUE THREAD

**Issue by ivanbrens** [6px-io/6px-api-docs#7]
Hey Guys,

Building out my webapp with your service here and am getting some errors on upload because some test images exceed the max file size allowed on the API.  What is the max image size you guys allow? ...I can't find this in the docs, I may have missed it. Currently working with the client-side js library, also I checked API docs.

I see that the images are compressed since the image sizes are different from at-rest on my local pc and what you guys show "processed".  

You guys have any recommendations how to best tackle this validation, perhaps with the client-side js library?

Thanks.  Great service BTW

**Comment by nparsons08** [comment]
Happy to help. Out of curiousity, how large is the file you're sending up
and what's the format? Can you attach the original image and your payload?

**Comment by ibrens** [comment]
This is the original image:

![3](https://cloud.githubusercontent.com/assets/8837725/7015754/17bbc138-dca7-11e4-8996-3fec699f41dc.jpg)

The size is 1,843 KB

Not exactly sure how you want to see the payload as it would probably scroll off the screen but it is a the base64 encoded output as this function would deliver:

var fileReader = new FileReader();
        fileReader.readAsDataURL(file);

it is being uploaded with your client-side js library.

**Comment by ibrens** [comment]
Any update on this?

**Comment by nparsons08** [comment]
Sorry for the lack of response. No excuse there. We're still looking into
the issue as it's one we haven't seen yet. Expect an update to follow. I
apologize for the delay.
ᐧ
